[package]
name = "l"
version = "0.1.0"
authors = ["Solomon Jackson <sugarfi@sugarfi.dev>"]
edition = "2018"

[build-dependencies] # <-- We added this and everything after!
lalrpop = { version = "0.19.0", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"
